apiVersion: v1
kind: Service
metadata:
  name: hivebox-service
  namespace: hivebox
spec:
  type: ClusterIP
  selector:
    app: hivebox
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888