apiVersion: v1
kind: Pod
metadata:
  name: hivebox
  labels:
    app: hivebox
  namespace: hivebox
spec:
  containers:
    - name: hivebox
      image: sag0108/hivebox:0.0.1
      ports:
        - containerPort: 8888
      envFrom:
        - secretRef:
            name: forecast-api-secret
